const fs=require('fs');
const path=require('path');
const {Worker}=require('worker_threads');
const crypto=require('crypto');
const ROOT=process.cwd();
const PLUGIN_DIR=path.join(ROOT,'plugins');
const WORKER_FILE=path.join(ROOT,'workers','trillions.worker.js');
const HYBRID_EVO={name:'TRILLIONS_HYBRID_RUNTIME_EVO',version:'V1',mode:'HYBRID_CORE_MODULAR_BACKEND_WORKERS_PLUGINS_REGISTRY_AUDIT',doctrine:['MONOLITH_STABLE','MODULAR_BACKEND','WORKER_POOL','PLUGIN_SYSTEM','REGISTRY_AUDIT','REAL_OR_UNAVAILABLE','NO_FAKE_METRICS','SAFE_REPAIR_ONLY']};
const workerPool={jobs:new Map(),history:[],maxWorkers:Math.max(1,Number(process.env.TRILLIONS_WORKER_POOL||Math.min(require('os').cpus().length||1,4)))};
function now(){return new Date().toISOString()}
function safe(x,n=12000){return String(x??'').slice(0,n)}
function listExpressRoutes(app){try{return (app._router&&app._router.stack||[]).filter(x=>x.route&&x.route.path).map(x=>({path:x.route.path,methods:Object.keys(x.route.methods)}));}catch(e){return []}}
function pluginFiles(){try{return fs.readdirSync(PLUGIN_DIR).filter(f=>f.endsWith('.plugin.js')).map(f=>path.join(PLUGIN_DIR,f));}catch(e){return []}}
function loadPlugins(app,ctx={}){const out=[];for(const file of pluginFiles()){try{delete require.cache[require.resolve(file)];const p=require(file);if(p&&typeof p.register==='function')p.register(app,ctx);out.push({file:path.basename(file),name:p.name||path.basename(file),version:p.version||null,status:'LOADED',routes:p.routes||[]});}catch(e){out.push({file:path.basename(file),status:'ERROR',error:e.message});}}return out}
function runWorker(task={},timeout=15000){return new Promise(resolve=>{const id='w_'+Date.now().toString(36)+'_'+crypto.randomBytes(3).toString('hex');const started=Date.now();if(!fs.existsSync(WORKER_FILE))return resolve({ok:false,id,error:'worker_file_missing',worker_file:WORKER_FILE});let done=false;const w=new Worker(WORKER_FILE,{workerData:{id,task}});const timer=setTimeout(()=>{if(done)return;done=true;try{w.terminate()}catch(e){}resolve({ok:false,id,error:'worker_timeout',timeout_ms:timeout,duration_ms:Date.now()-started});},timeout);w.on('message',msg=>{if(done)return;done=true;clearTimeout(timer);workerPool.history.push({id,time:now(),task:task.type||'unknown',ok:!!msg.ok,duration_ms:Date.now()-started});while(workerPool.history.length>100)workerPool.history.shift();resolve({...msg,id,duration_ms:Date.now()-started});});w.on('error',e=>{if(done)return;done=true;clearTimeout(timer);resolve({ok:false,id,error:e.message,duration_ms:Date.now()-started});});});}
function registryAudit(app){const routes=listExpressRoutes(app);let declared=[];try{const f=path.join(ROOT,'TRILLIONS_ULTIMATE_API_CATALOG_REGISTRY.json');if(fs.existsSync(f)){const j=JSON.parse(fs.readFileSync(f,'utf8'));declared=(j.routes||j.all_routes||[]).map(x=>typeof x==='string'?x:x.path).filter(Boolean)}}catch(e){}const mounted=new Set(routes.map(r=>r.path));const missing=declared.filter(r=>!mounted.has(r));return {time:now(),hybrid:HYBRID_EVO,express_routes:routes.length,declared_routes:declared.length,missing_count:missing.length,missing:missing.slice(0,100),status:missing.length?'PARTIAL':'FULLY_REGISTERED'};}
function registerHybridEvo(app,ctx={}){const loaded=loadPlugins(app,{...ctx,HYBRID_EVO,runWorker});app.get('/api/hybrid-evo',(req,res)=>res.json({time:now(),hybrid:HYBRID_EVO,backend:'MODULAR_LAYER_ACTIVE',plugins:loaded,worker_pool:{maxWorkers:workerPool.maxWorkers,history:workerPool.history.slice(-10)}}));app.get('/api/hybrid-evo/health',(req,res)=>res.json({ok:true,time:now(),hybrid:HYBRID_EVO.name,monolith:'STABLE_CORE',backend:'ACTIVE',plugins:pluginFiles().length,worker_file:fs.existsSync(WORKER_FILE),registry_audit:'/api/hybrid-evo/registry-audit'}));app.get('/api/hybrid-evo/plugins',(req,res)=>res.json({time:now(),plugins:loadPlugins(app,{...ctx,HYBRID_EVO,runWorker})}));app.get('/api/hybrid-evo/registry-audit',(req,res)=>res.json(registryAudit(app)));app.get('/api/hybrid-evo/worker-pool',(req,res)=>res.json({time:now(),pool:workerPool,worker_file:WORKER_FILE,exists:fs.existsSync(WORKER_FILE)}));app.post('/api/hybrid-evo/worker/run',async(req,res)=>res.json(await runWorker(req.body&&req.body.task||{type:'noop'},Number(req.body&&req.body.timeout||15000))));app.get('/api/hybrid-evo/worker/benchmark',async(req,res)=>res.json(await runWorker({type:'typedarray',size:Number(req.query.size||500000)},15000)));return {loaded};}
module.exports={HYBRID_EVO,registerHybridEvo,runWorker,registryAudit,loadPlugins};
